# Generated by Django 5.2.5 on 2025-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_detail_created_at_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('on_hold', 'Приостановлена'), ('cancelled', 'Отменена')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
